TEXC=pdflatex

all:
	find . -type f -name "*.tex" -exec $(TEXC) "{}" \; > /dev/null
	find . -type f -name "*.tex" -exec $(TEXC) "{}" \; > /dev/null
	find . -type f -name "*.tex" -exec $(TEXC) "{}" \; > /dev/null
	find . -type f -name "*.tex" -exec $(TEXC) "{}" \; > /dev/null
	find . -type f -name "*.tex" -exec $(TEXC) "{}" \; > /dev/null